package com.richdougherty.minstrel

final case class Op(name: String, code: Int)
object Op {
  val Halt = Op("halt", 0)
  val Push = Op("push", 1)
  val Pop = Op("pop", 2)
  val Dup = Op("dup", 3)
  val Rot = Op("rot", 4)
  val Ret = Op("ret", 5)
  val Jmp = Op("jmp", 6)
  val Call = Op("call", 7)
  val Neg = Op("neg", 8)
  val Bnot = Op("bnot", 9)
  val Not = Op("not", 10)
  val Add = Op("add", 11)
  val Sub = Op("sub", 12)
  val Mul = Op("mul", 13)
  val Div = Op("div", 14)
  val Mod = Op("mod", 15)
  val Bor = Op("bor", 16)
  val Band = Op("band", 17)
  val Bxor = Op("bxor", 18)
  val Shl = Op("shl", 19)
  val Sshr = Op("sshr", 20)
  val Zshr = Op("zshr", 21)
  val Lt = Op("lt", 22)
  val Lte = Op("lte", 23)
  val Gt = Op("gt", 24)
  val Gte = Op("gte", 25)
  val Eq = Op("eq", 26)
  val Ne = Op("ne", 27)
  val Acos = Op("acos", 28)
  val Atan = Op("atan", 29)
  val Cos = Op("cos", 30)
  val Sin = Op("sin", 31)
  val Tan = Op("tan", 32)
  val Ceil = Op("ceil", 33)
  val Floor = Op("floor", 34)
  val Exp = Op("exp", 35)
  val Log = Op("log", 36)
  val Sqrt = Op("sqrt", 37)
  val Abs = Op("abs", 38)
  val Atan2 = Op("atan2", 39)
  val Imul = Op("imul", 40)
  val U8Store = Op("u8store", 41)
  val U8Load = Op("u8load", 42)
  val I8Store = Op("i8store", 43)
  val I8Load = Op("i8load", 44)
  val I16Store = Op("i16store", 45)
  val I16Load = Op("i16load", 46)
  val I32Store = Op("i32store", 47)
  val I32Load = Op("i32load", 48)
  val F32Store = Op("f32store", 49)
  val F32Load = Op("f32load", 50)
  val F64Store = Op("f64store", 51)
  val F64Load = Op("f64load", 52)

  val all = Seq(Halt, Push, Pop, Dup, Rot, Ret, Jmp, Call, Neg, Bnot, Not, Add, Sub, Mul, Div, Mod, Bor, Band, Bxor, Shl, Sshr, Zshr, Lt, Lte, Gt, Gte, Eq, Ne, Acos, Atan, Cos, Sin, Tan, Ceil, Floor, Exp, Log, Sqrt, Abs, Atan2, Imul, U8Store, U8Load, I8Store, I8Load, I16Store, I16Load, I32Store, I32Load, F32Store, F32Load, F64Store, F64Load)

  val byName: Map[String, Op] = Map(all.map(op => op.name -> op): _*)
  val byCode: Map[Int, Op] = Map(all.map(op => op.code -> op): _*)

}